# Generated by Django 4.2 on 2023-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('surgery', models.CharField(max_length=255)),
                ('medication', models.CharField(max_length=255)),
            ],
        ),
    ]
